---

 - hosts: all
   gather_facts: true
   become: yes
   become_user: root

   tasks:
     - name: Install tcpflow package
       package:
         name: tcpflow
         state: present

     - name: Collect PCAP file from server
       fetch:
         src: /home/villena/executablePCAPfile.pcapng
         dest: /home/villena/HOA_8.1/pcap_dest/
         flat: yes

 - hosts: all
   connection: local
   gather_facts: false
   tasks:
     - name: Extract executable from PCAP file
       shell: "tcpflow -r /home/villena/HOA_8.1/pcap8.1/executablePCAPfile.pcapng -o /home/villena/HOA_8.1/pcap8.1_out/"
       args:
         creates: /home/villena/HOA_8.1/pcap8.1_out/executable.exe

     - name: Debug .exe file
       command: "cat /home/villena/HOA_8.1/pcap8.1_out/report.xml"
       register: cat_output
       changed_when: false

     - debug:
         var: cat_output.stdout_lines
